language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env: SCRIPT=vendor/bin/simple-phpunit

matrix:
    fast_finish: true
    include:
        - php: 5.3
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak SCRIPT=phpunit
        - php: 5.6
          env: SYMFONY_VERSION='2.8.*@dev' DEPENDENCIES=dev COMPOSER_FLAGS="--prefer-stable" SCRIPT=phpunit
        - php: 5.6
          env: DEPENDENCIES=dev SCRIPT=phpunit

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle=$SYMFONY_VERSION; fi
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install: composer update $COMPOSER_FLAGS

script:
    - $SCRIPT --coverage-text
